basePath: /api
definitions:
  types.GetCaptchaResp:
    properties:
      id:
        description: 验证码ID
        type: string
      src:
        description: 验证码base64
        type: string
    required:
    - id
    - src
    type: object
  types.GetUserInfoResp:
    properties:
      avatar:
        description: 用户头像
        type: string
      real_name:
        description: 用户名称
        type: string
      status:
        description: 用户状态
        type: boolean
    required:
    - avatar
    - real_name
    - status
    type: object
  types.GetUserListResp:
    properties:
      book_ident:
        description: 用户状态
        type: string
      book_name:
        description: 用户名称
        type: string
      created_at:
        description: 用户头像
        type: string
    required:
    - book_ident
    - book_name
    - created_at
    type: object
  types.JsonResp:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      time:
        type: integer
    required:
    - code
    - data
    - msg
    - time
    type: object
  types.UserLoginReq:
    properties:
      captcha_code:
        description: 验证码
        type: string
      captcha_id:
        description: 验证码ID
        type: string
      password:
        description: 用户名称
        type: string
      username:
        description: 用户名称
        type: string
    required:
    - captcha_code
    - captcha_id
    - password
    - username
    type: object
  types.UserLoginResp:
    properties:
      token:
        description: jwt token
        type: string
    required:
    - token
    type: object
host: 127.0.0.1:3000
info:
  contact:
    name: whileSun
  description: go-server服务接口文档
  title: 接囗文档
  version: "1.0"
paths:
  /v1/captcha/get:
    get:
      description: 登录验证码
      operationId: getCaptcha
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/types.JsonResp'
            - properties:
                data:
                  $ref: '#/definitions/types.GetCaptchaResp'
              type: object
      tags:
      - sys
  /v1/user/info/get:
    get:
      description: 获取用户信息
      operationId: getUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/types.JsonResp'
            - properties:
                data:
                  $ref: '#/definitions/types.GetUserInfoResp'
              type: object
      tags:
      - user
  /v1/user/list/get:
    get:
      description: 获取用户列表
      operationId: getUserList
      parameters:
      - description: 验证码
        in: query
        name: captcha_code
        required: true
        type: string
      - description: 验证码ID
        in: query
        name: captcha_id
        required: true
        type: string
      - description: 用户名称
        in: query
        name: password
        required: true
        type: string
      - description: 用户名称
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/types.JsonResp'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/types.GetUserListResp'
                  type: array
              type: object
      tags:
      - user
  /v1/user/login:
    post:
      description: 登录接口
      operationId: userLogin
      parameters:
      - description: UserLoginReq
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/types.JsonResp'
            - properties:
                data:
                  $ref: '#/definitions/types.UserLoginResp'
              type: object
      tags:
      - user
  /v1/user/out.login:
    get:
      description: 用户退出接口
      operationId: userOutLogin
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/types.JsonResp'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
      tags:
      - user
swagger: "2.0"
