name: go-server
port: 3000
log:
  stdout: true
db:
  type: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 123456!
  name: blog_oms
  maxIdleConn: 5
  maxOpenConn: 20
  log: true
app:
  # 下面参数修改要重新初始化数据库
  saltPwd: ws_oms
  initPwd: 123456
  userSuperName: system
  roleSuperName: super_admin