# This workflow will build a golang project

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 添加go环境
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: 添加node环境
          uses: actions/setup-node@v3
          with:
            node-version: 16.x

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.0

      - name: react打包
        run: |
          cd react-client
          pnpm install
          pnpm build

      - name: go编译打包
        run: |
          cd .. && cd go-server
          go env -w CGO_ENABLED=0 && GOOS=linux GOARCH=amd64 go build -v ./...

      # https://github.com/appleboy/scp-action
      - name: 部署到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # 公网ip
          username: ${{ secrets.REMOTE_USERNAME }} # 用户名
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # 密码
          source: "dist/*,go-server" # 发送文件
          target: "/home/go-project" # 目标目录

      # https://github.com/appleboy/ssh-action
      - name: 重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            docker restart go-web